### ISSUE TITLE
Bump windows binaries to 2.0.5

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/ECOS.jl#47]
Re: https://github.com/JuliaOpt/ECOS.jl/pull/46
@tkelman, I know julia master is broken right now, but when you get a chance would appreciate bumping the windows binaries. The failing test on win32 (https://github.com/JuliaOpt/ECOS.jl/issues/33#issuecomment-155213055) shouldn't hold this up as long as the ECOS.jl tests pass.

**Comment by tkelman** [comment]
I don't remember whether I needed any particular flags to build these. I may have written that down somewhere in an issue or PR, can you find it? Should be possible to cross compile too, so you wouldn't have to wait for me on this.

**Comment by mlubin** [comment]
Here's what I could dig up: https://github.com/JuliaOpt/ECOS.jl/issues/7#issuecomment-50522433

**Comment by mlubin** [comment]
@tkelman, could I bug you again for this?
Pajarito will be failing on AppVeyor until ECOS gets updated.

**Comment by tkelman** [comment]
Time I spend on this is time that doesn't get spent posting a design and working on the code for a replacement for bindeps. What have you tried.

**Comment by juan-pablo-vielma** [comment]
This error will be fixed by #76 partly by removing the `::Vector{Int}` from 
https://github.com/JuliaOpt/ECOS.jl/blob/23594975c8506bf4905b24120b0dd360aa9e24be/src/MPBWrapper.jl#L268
and
https://github.com/JuliaOpt/ECOS.jl/blob/23594975c8506bf4905b24120b0dd360aa9e24be/src/MPBWrapper.jl#L334
However, the actual error is form an `Int64` that should be `Int` in this MathProgBase.jl test:
https://github.com/JuliaOpt/MathProgBase.jl/blob/85c32c911e85c97c4d639f534c9bc56f0f09b21a/test/conicinterface.jl#L795-L796
Will do a PR for this in MPB just in case.

**Comment by mlubin** [comment]
Closed by #76
